version: '3.8'

services:
  database:
    build: ./database
    container_name: database
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - zeetms-network

  backend:
    build: ./backend
    container_name: backend
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
    depends_on:
      - database
    ports:
      - "8000:8000"
    volumes:
      - uploads:/app/uploads  # Add volume for uploads
    networks:
      - zeetms-network

  frontend:
    build: ./frontend
    container_name: frontend
    environment:
      - REACT_APP_API_URL=http://10.118.1.7/api
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - zeetms-network

  webserver:
    build: ./webserver
    container_name: webserver
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
    networks:
      - zeetms-network

networks:
  zeetms-network:
    driver: bridge

volumes:
  db-data:
  uploads:  