events {}

http {
  resolver 127.0.0.11 valid=10s;

  upstream frontend {
    server frontend:3000;
  }

  upstream backend {
    server backend:8000;
  }

  server {
    listen 80;
    server_name 10.118.1.7;

    location / {
      proxy_pass http://frontend;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/ {
      proxy_pass http://backend/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}